name: Docker Build and Push - Web App

on:
  release:
    types: [ published ]
  push:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
        
#       - name: Configure environment name
#         id: env-name
#         run: |
#           echo "::set-env name=Num::$(cat number)"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: var setup
        run: echo "num=$(cat number)" >> $GITHUB_ENV


      - name: check var
        run: echo $num
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: bekdemo/node-webapp:${{ env.num }}
